// Generated by Xata Codegen 0.29.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "masterclasses",
    columns: [
      { name: "title", type: "string" },
      { name: "dates", type: "string" },
      { name: "formLink", type: "string" },
      { name: "paymentLink", type: "string" },
      { name: "remaining", type: "string" },
      { name: "description", type: "text" },
      { name: "intermediateTimings", type: "string" },
      { name: "intermediateDownloadLink", type: "string" },
      { name: "advancedTimings", type: "string" },
      { name: "advancedDownloadLink", type: "string" },
      { name: "localFeesNumbers", type: "string" },
      { name: "localFeesWords", type: "string" },
      { name: "globalFeesNumbers", type: "string" },
      { name: "globalFeesWords", type: "string" },
    ],
  },
  {
    name: "users",
    columns: [
      { name: "name", type: "string" },
      { name: "timezone", type: "string" },
      { name: "batch", type: "string" },
      { name: "email", type: "email" },
      { name: "reminder", type: "bool", defaultValue: "true" },
    ],
  },
  {
    name: "emails",
    columns: [
      { name: "name", type: "string" },
      { name: "subject", type: "string" },
      { name: "preview", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Masterclasses = InferredTypes["masterclasses"];
export type MasterclassesRecord = Masterclasses & XataRecord;

export type Users = InferredTypes["users"];
export type UsersRecord = Users & XataRecord;

export type Emails = InferredTypes["emails"];
export type EmailsRecord = Emails & XataRecord;

export type DatabaseSchema = {
  masterclasses: MasterclassesRecord;
  users: UsersRecord;
  emails: EmailsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Yogesh-Samsi-s-workspace-7dkagb.eu-central-1.xata.sh/db/ysadmin",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
